from enum import IntEnum


class TrackerPosition(IntEnum):
    """
    https://github.com/SlimeVR/SlimeVR-Server/blob/394c1dd43833e6ffc1f65ee4e9efa764f027391c/server/core/src/main/java/dev/slimevr/tracking/trackers/TrackerPosition.kt
    """
    HEAD = 1
    NECK = 2
    UPPER_CHEST = 3
    CHEST = 4
    WAIST = 5
    HIP = 6
    LEFT_UPPER_LEG = 7
    RIGHT_UPPER_LEG = 8
    LEFT_LOWER_LEG = 9
    RIGHT_LOWER_LEG = 10
    LEFT_FOOT = 11
    RIGHT_FOOT = 12
    LEFT_LOWER_ARM = 13
    RIGHT_LOWER_ARM = 14
    LEFT_UPPER_ARM = 15
    RIGHT_UPPER_ARM = 16
    LEFT_HAND = 17
    RIGHT_HAND = 18
    LEFT_SHOULDER = 19
    RIGHT_SHOULDER = 20
    LEFT_THUMB_METACARPAL = 21
    LEFT_THUMB_PROXIMAL = 22
    LEFT_THUMB_DISTAL = 23
    LEFT_INDEX_PROXIMAL = 24
    LEFT_INDEX_INTERMEDIATE = 25
    LEFT_INDEX_DISTAL = 26
    LEFT_MIDDLE_PROXIMAL = 27
    LEFT_MIDDLE_INTERMEDIATE = 28
    LEFT_MIDDLE_DISTAL = 29
    LEFT_RING_PROXIMAL = 30
    LEFT_RING_INTERMEDIATE = 31
    LEFT_RING_DISTAL = 32
    LEFT_LITTLE_PROXIMAL = 33
    LEFT_LITTLE_INTERMEDIATE = 34
    LEFT_LITTLE_DISTAL = 35
    RIGHT_THUMB_METACARPAL = 36
    RIGHT_THUMB_PROXIMAL = 37
    RIGHT_THUMB_DISTAL = 38
    RIGHT_INDEX_PROXIMAL = 39
    RIGHT_INDEX_INTERMEDIATE = 40
    RIGHT_INDEX_DISTAL = 41
    RIGHT_MIDDLE_PROXIMAL = 42
    RIGHT_MIDDLE_INTERMEDIATE = 43
    RIGHT_MIDDLE_DISTAL = 44
    RIGHT_RING_PROXIMAL = 45
    RIGHT_RING_INTERMEDIATE = 46
    RIGHT_RING_DISTAL = 47
    RIGHT_LITTLE_PROXIMAL = 48
    RIGHT_LITTLE_INTERMEDIATE = 49
    RIGHT_LITTLE_DISTAL = 50
